package:
  name: 'nionswift-io'
  version: '15.4.1'

source:
  git_rev: 15.4.1
  git_url: https://github.com/nion-software/nionswift-io.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.11
    - niondata >=15.8,<16.0
    - nionutils >=4.13,<5.0
    - numpy >=2.0,<3.0
    - pytz
    - tifffile

test:
  imports:
    - nionswift_plugin.DM_IO
    - nionswift_plugin.DM_IO.test
    - nionswift_plugin.TIFF_IO
    - nionswift_plugin.TIFF_IO.test

about:
  home: https://github.com/nion-software/nionswift-io
  license: Apache-2.0
  summary: Nion UI classes.
  description: "A package for adding I/O handlers to Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
